# Generated by Django 4.0.5 on 2023-01-13 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_vehicle_log_image_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-exit', '-entry')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.AlterField(
            model_name='log',
            name='onduty',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='onduty_user', to='base.user'),
        ),
    ]
